// ZIP生成API
import { NextResponse } from 'next/server';
import JSZip from 'jszip';
import { generateHtml, generateCss } from '@/lib/templates';
import type { LP } from '@/types/lp';

export async function POST(request: Request) {
    try {
        const { lp } = await request.json() as { lp: LP };

        if (!lp) {
            return NextResponse.json({ error: 'LP data is required' }, { status: 400 });
        }

        // ZIP生成
        const zip = new JSZip();

        // index.html
        const html = generateHtml(lp);
        zip.file('index.html', html);

        // style.css
        const css = generateCss();
        zip.file('style.css', css);

        // assets フォルダ（プレースホルダー）
        const assetsFolder = zip.folder('assets');

        // README.md
        const readme = `# ${lp.title}

Generated by LP Builder

## ファイル構成
- index.html - メインHTMLファイル
- style.css - スタイルシート
- assets/ - 画像ファイル用フォルダ

## 使い方
1. このZIPを解凍してください
2. index.htmlをブラウザで開くか、お好みのサーバーにデプロイしてください

## カスタマイズ
- 画像を差し替える場合は、assetsフォルダに画像を追加し、HTMLを編集してください
- スタイルを変更する場合は、style.cssを編集してください

Generated at: ${new Date().toISOString()}
`;
        zip.file('README.md', readme);

        // 使用されている画像URLからプレースホルダーを作成（オプション）
        if (assetsFolder) {
            assetsFolder.file('.gitkeep', '');
        }

        // ZIPを生成
        const zipBlob = await zip.generateAsync({
            type: 'nodebuffer',
            compression: 'DEFLATE',
            compressionOptions: { level: 9 }
        });

        // レスポンスを返す
        return new NextResponse(zipBlob, {
            status: 200,
            headers: {
                'Content-Type': 'application/zip',
                'Content-Disposition': `attachment; filename="${lp.title.replace(/[^a-zA-Z0-9]/g, '_')}.zip"`,
            },
        });
    } catch (error) {
        console.error('Export error:', error);
        return NextResponse.json({ error: 'Failed to generate ZIP' }, { status: 500 });
    }
}
